services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres_shadow:
    container_name: postgres_shadow_db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shadow
    volumes:
      - postgres_shadow_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  postgres_shadow_data:
